name: Generate Documentation
on:
  workflow_dispatch:
jobs:
  generate-docs:
    runs-on: macos-15
    name: Generate Documentation
    steps:
      - uses: actions/checkout@v4
      - name: Generate documentation
        run: |
          swift package --allow-writing-to-directory ./docs \
              generate-documentation --target Ladybug --disable-indexing \
              --output-path ./docs \
              --transform-for-static-hosting \
              --hosting-base-path /api-docs/swift
      # upload-artifact rejects certain characters in the path, so we zip the 
      # documentation directory before uploading.
      - name: Zip documentation
        run: |
          mv docs swift
          zip -r swift-ladybug-docs.zip swift
      - name: Upload documentation
        uses: actions/upload-artifact@v4
        with:
          name: swift-ladybug-docs
          path: swift-ladybug-docs.zip
  update-docs:
    runs-on: ubuntu-22.04
    name: Update Documentation Repository
    needs: generate-docs
    steps:
      - uses: actions/checkout@v4
        with:
          repository: ladybugdb/api-docs
          token: ${{ secrets.DOC_PUSH_TOKEN }}
          path: api-docs
      - name: Remove old documentations
        run: |
          rm -rf api-docs/swift
      - name: Download Swift docs
        uses: actions/download-artifact@v4
        with:
          name: swift-ladybug-docs
          path: api-docs
      - name: Unzip Swift docs
        run: |
          cd api-docs
          unzip swift-ladybug-docs.zip
          rm -f swift-ladybug-docs.zip
      - name: Push changes
        working-directory: api-docs
        run: |
          git checkout -b "swift-documentation-update-${{ github.sha }}"
          git config --global user.name "CI User"
          git config --global user.email "ci@ladybugdb.com"
          git add .
          git commit -m "Update Swift API documentations"
          git push -u origin "swift-documentation-update-${{ github.sha }}"
      - name: Create pull request
        working-directory: api-docs
        run: |
          echo "${{ secrets.DOC_PUSH_TOKEN }}" > token.txt
          gh auth login --with-token < token.txt
          rm -rf token.txt
          gh pr create \
            --body "Action triggered by CI workflow." \
            --title "Update Swift API documentations" \
            --head "swift-documentation-update-${{ github.sha }}" \
            --base "main"
